"""APPD 中文文案表。"""

from __future__ import annotations

from typing import Dict

STRINGS_ZH_CN: Dict[str, str] = {
    "app.title": "轴向柱塞泵设计软件（APPD）",
    "menu.file": "文件(F)",
    "menu.file.new_design": "开始设计(N)",
    "menu.file.exit_design": "退出设计(E)",
    "menu.file.open_model": "打开泵型号(O)",
    "menu.file.save": "保存",
    "menu.file.save_as": "另存为",
    "menu.file.exit_program": "退出程序(X)",
    "menu.view": "视图(V)",
    "menu.view.standard_toolbar": "标准工具条(T)",
    "menu.view.window_toolbar": "窗口控制工具条(S)",
    "menu.tools": "工具",
    "menu.tools.material_database": "材料数据库",
    "menu.tools.export_word": "输出到Word",
    "menu.tools.export_3d": "输出三维模型",
    "menu.tools.hypneu": "与HyPneu联合仿真",
    "menu.tools.optimize": "优化工具",
    "menu.tools.material_match": "材料配合",
    "menu.tools.defaults": "默认参数",
    "menu.server": "访问服务器",
    "menu.server.upload": "上传设计型号",
    "menu.server.download": "下载设计型号",
    "menu.help": "帮助(H)",
    "menu.help.about": "关于APPD软件(A)",
    "menu.help.user_manual": "用户手册",
    "menu.help.tech_manual": "技术手册",
    "toolbar.standard": "标准工具条(T)",
    "toolbar.window": "窗口控制工具条(S)",
    "nav.title": "设计页面选择",
    "nav.item.appd_main": "轴向柱塞泵（主）",
    "nav.item.tehl": "摩擦副/TEHL",
    "nav.item.contamination": "污染",
    "nav.item.servo_valve": "电液伺服阀",
    "nav.item.cycloid_pump": "摆线泵",
    "nav.item.gear_pump": "齿轮泵",
    "nav.item.hydraulic_cylinder": "作动缸",
    "module.placeholder": "本模块计算逻辑将在后续阶段实现",
    "tehl.module": "摩擦副/TEHL",
    "tehl.tab.pressures": "压力场",
    "tehl.tab.film_3d": "膜厚3D",
    "tehl.tab.thermal": "热分析",
    "tehl.placeholder": "本模块计算逻辑将在后续阶段实现",
    "module.appd_main.title": "轴向柱塞泵（主）",
    "module.tehl.title": "摩擦副/TEHL",
    "module.contamination.title": "污染",
    "module.servo_valve.title": "电液伺服阀",
    "module.cycloid_pump.title": "摆线泵",
    "module.gear_pump.title": "齿轮泵",
    "module.hydraulic_cylinder.title": "作动缸",
    "load_spectrum.title": "载荷谱",
    "load_spectrum.table.index": "序号",
    "load_spectrum.table.max_pressure": "最大压力(MPa)",
    "load_spectrum.table.frequency": "出现频率(1/小时)",
    "load_spectrum.rated_pressure": "额定压力",
    "units.mpa": "MPa",
    "panel.actions.cylinder_life": "缸体寿命",
    "panel.actions.bearing_life": "轴承寿命",
    "panel.actions.pump_life": "泵寿命",
    "panel.actions.pump_life_alt": "泵寿命…",
    "panel.actions.trial_unavailable": "试用版不可用",
    "dialog.not_implemented.title": "提示",
    "dialog.not_implemented.body": "未实现",
    "dialog.file.error_title": "文件操作失败",
    "dialog.file.save_success_title": "保存成功",
    "dialog.file.save_success_body": "项目已保存。",
    "dialog.file.filter": "APPD 项目文件 (*.apdd.json)",
}


def get_text(key: str) -> str:
    return STRINGS_ZH_CN[key]
